services:
  postgres:
    image: postgres:16
    container_name: ph_flood_postgres
    environment:
      POSTGRES_DB: ph_flood_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: